Make possible to run on Windows
epiphany-platform/m-generic-epiphany-on-aks pull request #3
Opened 2020-11-18 17:18 UTC by to-bar

- Ensure SSH key permissions
- Adjust UID and GID of epiuser
- Print environment variables for `apply-azepi`
- Support docker.sock for Git Bash on Windows
- Use epicli v0.8.0

2020-11-18 17:42 UTC, sk4zuzu requested changes
:heart_eyes:

2020-11-18 17:42 UTC, sk4zuzu commented on resources/azepi/apply.py
> +    key_path_from_share = os.path.join(v["shared_dir"], "vms_rsa")
Would be nice to keep the convention and use `pathlib.Path` here as well :+1::innocent:
```suggestion
    key_path_from_share = v["shared_dir"] / "vms_rsa"
```

2020-11-18 17:42 UTC, sk4zuzu commented on resources/azepi/apply.py
> +    key_path_from_spec = cluster["specification"]["admin_user"]["key_path"]
```suggestion
    key_path_from_spec = get_path(cluster["specification"]["admin_user"]["key_path"])
```

2020-11-18 17:42 UTC, sk4zuzu commented on resources/azepi/apply.py
> +            cp --verbose {key_path_from_share}* {os.path.dirname(key_path_from_spec)}
```suggestion
            cp --verbose {key_path_from_share}* {key_path_from_spec.parent)}
```

2020-11-18 17:42 UTC, sk4zuzu commented on resources/azepi/apply.py
> +import os
```suggestion
```

2020-11-18 18:21 UTC, sk4zuzu submitted a review, later dismissed
:hugs:

2020-11-18 18:36 UTC, sk4zuzu submitted a review, later dismissed
:cat2:

2020-11-19 08:45 UTC, sk4zuzu requested changes
:thinking:

2020-11-19 08:45 UTC, sk4zuzu commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +        cache_dir = os.getenv("CACHE_DIR", "/shared")
```suggestion
        cache_dir_env = os.getenv("CACHE_DIR", "/shared")
```

2020-11-19 08:45 UTC, sk4zuzu commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +        external_cache_dir = pathlib.Path(cache_dir).resolve()
```suggestion
        external_cache_dir = pathlib.Path(cache_dir_env).resolve()
```

2020-11-19 08:45 UTC, sk4zuzu commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +        if not external_cache_dir.exists() and pathlib.PureWindowsPath(cache_dir).is_absolute():
```suggestion
        if not external_cache_dir.exists() and pathlib.PureWindowsPath(cache_dir_env).is_absolute():
```

2020-11-19 08:45 UTC, sk4zuzu commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +            external_cache_dir = pathlib.Path(cache_dir)
```suggestion
            external_cache_dir = pathlib.Path(cache_dir_env)
```

2020-11-19 09:07 UTC, sk4zuzu approved these changes
:monkey:

2020-11-19 14:25 UTC, erzetpe approved these changes

2020-11-19 14:46 UTC, merged